# HarmoniusApp.cmake Top-level API for assembling a source-free .app / .ipa
# bundle from harmonius_add_module libraries.
#
# Design rules enforced here: • No SOURCES — all code lives in
# harmonius_add_module libraries. • The entry point (Swift @main) is provided
# via a generated main.swift. • MACOSX_BUNDLE is never set on any target.
#
# Public API: harmonius_add_app_bundle(<TARGET> PLATFORM     macos | ios |
# ios-simulator LIBRARIES    <lib ...>           # harmonius_add_module targets
# to link INFO_PLIST   <path> ENTRY_MODULE <module-name>       # Swift module
# containing the App type ENTRY_POINT  <TypeName>          # Swift type
# conforming to App (no @main) [BUNDLE_ID   <id>]               # informational;
# plist wins [RESOURCES   <file ...>] [FRAMEWORKS  <name ...>]         # extra
# frameworks beyond platform defaults )
#
# Platform-default frameworks added automatically: macos            → AppKit ios
# → UIKit ios-simulator    → UIKit
#
# After calling harmonius_add_app_bundle, also call:
# harmonius_bundle_set_provisioning_profile(<TARGET> <path>) — iOS, optional
# harmonius_bundle_finalize(<TARGET>)        — assembles the .app directory
# harmonius_codesign_bundle(<TARGET>)        — optional, ad-hoc by default
# harmonius_bundle_install(<TARGET> ...)     — registers cmake install rule

cmake_minimum_required(VERSION 4.0)

include(HarmoniusBundle)
include(HarmoniusModule)

function(harmonius_add_app_bundle _target)
  cmake_parse_arguments(
    _APP "" "PLATFORM;INFO_PLIST;ENTRY_MODULE;ENTRY_POINT;BUNDLE_ID"
    "LIBRARIES;RESOURCES;FRAMEWORKS" ${ARGN})

  # -------------------------------------------------------------------------
  # Guard: no source code in the app bundle call
  # -------------------------------------------------------------------------
  foreach(_bad IN ITEMS SOURCES SWIFT_SOURCES CXX_SOURCES METAL_SOURCES)
    if(DEFINED "_APP_${_bad}")
      message(
        FATAL_ERROR
          "harmonius_add_app_bundle(${_target}): ${_bad} is not allowed. \
All source code must live in harmonius_add_module libraries.")
    endif()
  endforeach()

  if(NOT _APP_PLATFORM)
    message(
      FATAL_ERROR "harmonius_add_app_bundle(${_target}): PLATFORM is required \
(macos | ios | ios-simulator)")
  endif()
  if(NOT _APP_LIBRARIES)
    message(
      FATAL_ERROR "harmonius_add_app_bundle(${_target}): LIBRARIES is required")
  endif()
  if(NOT _APP_INFO_PLIST)
    message(
      FATAL_ERROR "harmonius_add_app_bundle(${_target}): INFO_PLIST is required"
    )
  endif()
  if(NOT _APP_ENTRY_MODULE)
    message(
      FATAL_ERROR
        "harmonius_add_app_bundle(${_target}): ENTRY_MODULE is required")
  endif()
  if(NOT _APP_ENTRY_POINT)
    message(
      FATAL_ERROR
        "harmonius_add_app_bundle(${_target}): ENTRY_POINT is required")
  endif()

  cmake_path(IS_RELATIVE _APP_INFO_PLIST _plist_rel)
  if(_plist_rel)
    set(_APP_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/${_APP_INFO_PLIST}")
  endif()

  # -------------------------------------------------------------------------
  # Generate a minimal main.swift that starts the SwiftUI / App lifecycle. The
  # @main attribute is NOT used; we call App.main() explicitly so that the entry
  # type can live in a static library module without @main.
  # -------------------------------------------------------------------------
  set(_stub_dir "${CMAKE_BINARY_DIR}/${_target}_app_stub")
  set(_stub_file "${_stub_dir}/main.swift")
  file(MAKE_DIRECTORY "${_stub_dir}")
  file(WRITE "${_stub_file}"
       "// Generated by harmonius_add_app_bundle — do not edit.\n"
       "import ${_APP_ENTRY_MODULE}\n" "${_APP_ENTRY_POINT}.main()\n")

  # -------------------------------------------------------------------------
  # Executable target (compiled from the generated stub only)
  # -------------------------------------------------------------------------
  set(_exe "${_target}_exe")
  add_executable("${_exe}" "${_stub_file}")

  set_target_properties("${_exe}" PROPERTIES Swift_MODULE_NAME "${_target}"
                                             OUTPUT_NAME "${_target}")

  harmonius_swift_cxx_apply_module("${_exe}")

  # -------------------------------------------------------------------------
  # Link all module libraries
  # -------------------------------------------------------------------------
  target_link_libraries("${_exe}" PRIVATE ${_APP_LIBRARIES})

  # -------------------------------------------------------------------------
  # Propagate include dirs from all transitive module deps to the stub
  # executable. Swift needs these to resolve Clang modules referenced by
  # .swiftmodule files in the dependency chain (e.g. HarmoniusShaderTypes
  # required by HarmoniusRendering.swiftmodule).
  # -------------------------------------------------------------------------
  _harmonius_collect_all_module_deps(_all_trans_deps ${_APP_LIBRARIES})
  set(_all_module_targets ${_APP_LIBRARIES} ${_all_trans_deps})
  foreach(_mod IN LISTS _all_module_targets)
    if(NOT TARGET "${_mod}")
      continue()
    endif()
    get_target_property(_mod_incs "${_mod}" INTERFACE_INCLUDE_DIRECTORIES)
    if(_mod_incs)
      target_include_directories("${_exe}" PRIVATE ${_mod_incs})
    endif()
    # Also forward Swift -Xcc -I flags
    get_target_property(_mod_copts "${_mod}" INTERFACE_COMPILE_OPTIONS)
    if(_mod_copts)
      target_compile_options("${_exe}" PRIVATE ${_mod_copts})
    endif()
  endforeach()

  # Force-load each module archive so that Swift runtime metadata and the
  # App.main() entry point are fully included in the final binary. Use SHELL: to
  # prevent CMake from deduplicating repeated -Xlinker tokens, which would
  # corrupt both the force_load and rpath linker flags.
  foreach(_lib IN LISTS _APP_LIBRARIES)
    target_link_options(
      "${_exe}" PRIVATE
      "SHELL:-Xlinker -force_load -Xlinker $<TARGET_FILE:${_lib}>")
  endforeach()

  # Collect transitive module dependencies and force-load them too
  _harmonius_collect_all_module_deps(_all_deps ${_APP_LIBRARIES})
  foreach(_dep IN LISTS _all_deps)
    if(TARGET "${_dep}")
      target_link_options(
        "${_exe}" PRIVATE
        "SHELL:-Xlinker -force_load -Xlinker $<TARGET_FILE:${_dep}>")
    endif()
  endforeach()

  # -------------------------------------------------------------------------
  # Platform-specific frameworks
  # -------------------------------------------------------------------------
  if(_APP_PLATFORM STREQUAL "macos")
    target_link_libraries("${_exe}" PRIVATE "-framework AppKit")
  else()
    target_link_libraries("${_exe}" PRIVATE "-framework UIKit")
  endif()

  foreach(_fw IN LISTS _APP_FRAMEWORKS)
    target_link_libraries("${_exe}" PRIVATE "-framework ${_fw}")
  endforeach()

  # -------------------------------------------------------------------------
  # Collect metallib targets from all linked modules (transitively)
  # -------------------------------------------------------------------------
  _harmonius_collect_module_metallibs(_ml_targets ${_APP_LIBRARIES})

  # -------------------------------------------------------------------------
  # Bundle assembly via HarmoniusBundle.cmake
  # -------------------------------------------------------------------------
  harmonius_bundle_init("${_target}" PLATFORM "${_APP_PLATFORM}" BASE_DIR
                        "${CMAKE_BINARY_DIR}")
  harmonius_bundle_set_info_plist("${_target}" "${_APP_INFO_PLIST}")
  harmonius_bundle_set_executable("${_target}" "${_exe}")

  if(_ml_targets)
    harmonius_bundle_add_metallibs("${_target}" ${_ml_targets})
  endif()

  if(_APP_RESOURCES)
    harmonius_bundle_add_resources("${_target}" ${_APP_RESOURCES})
  endif()
endfunction()

# ---------------------------------------------------------------------------
# Internal: recursively collect HARMONIUS_MODULE_DEPS from a list of targets.
# Used to gather ALL module archives that need to be force-loaded.
# ---------------------------------------------------------------------------
function(_harmonius_collect_all_module_deps _result_var)
  set(_all "")
  set(_visited "")
  set(_queue "${ARGN}")
  while(_queue)
    list(POP_FRONT _queue _mod)
    if("${_mod}" IN_LIST _visited)
      continue()
    endif()
    list(APPEND _visited "${_mod}")

    if(NOT TARGET "${_mod}")
      continue()
    endif()

    get_target_property(_deps "${_mod}" HARMONIUS_MODULE_DEPS)
    if(_deps)
      list(APPEND _all ${_deps})
      list(APPEND _queue ${_deps})
    endif()
  endwhile()
  list(REMOVE_DUPLICATES _all)
  set(${_result_var}
      "${_all}"
      PARENT_SCOPE)
endfunction()
